# render.yaml
services:
  - name: app
    type: web
    buildCommand: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      source venv/bin/activate
      gunicorn -b 0.0.0.0:8080 app:app
    env: {}
